spring:
  
  application:
    name: score-check    #service name
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://192.168.100.4:8761/eureka/
    lease:
      duration: 5