spring:
  datasource:
    #url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db
    url: jdbc:mysql://192.168.100.4:3306/db
    username: user
    password: password
  jpa:
    hibernate.ddl-auto: update
  application:
    name: loan-connect    #service name
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://192.168.100.4:8761/eureka/
    lease:
      duration: 5